package com.katruk.veiw;

public interface Const {

  int MIN_WEIGHT_OF_AMMUNITION = 0;
  int MAX_WEIGHT_OF_AMMUNITION = 200;
  int MIN_PRICE_OF_AMMUNITION = 0;
  int MAX_PRICE_OF_AMMUNITION = 1000000;
  int MIN_SKILL_OF_SHIELD = 0;
  int MAX_SKILL_OF_SHIELD = 1000;
  int MIN_SKILL_OF_ARMOR = 2;
  int MAX_SKILL_OF_ARMOR = 5000;

}
